version: "3"
services:
    test_mysql:
        container_name: test_mariadb
        build: ./mariadb
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: production_db
            MYSQL_USER: hoge
            MYSQL_PASSWORD: hogehoge
        ports:
          - 3306:3306


# networks:
#     vol1_network:
#         external: true
